# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kabe?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ayame
    password: ayame20#
#  sql:
#    init: # No database deployment data written, so this feature is not enabled for now
#      mode: never
#      schema-locations: classpath:db/schema.sql  # this feature is not enabled for now
#      data-locations: classpath:db/data.sql  # this feature is not enabled for now


# Mybatis-Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??sql??
  mapper-locations: classpath:com/example/kabesystem/mapper/*.java
  type-aliases-package: mapper??