#server.port: 7778


# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kabe?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ayame
    password: ayame20#
#  sql:
#    init: # No database deployment data written, so this feature is not enabled for now
#      mode: never
#      schema-locations: classpath:db/schema.sql  # this feature is not enabled for now
#      data-locations: classpath:db/data.sql  # this feature is not enabled for now
  mail:
    host: smtp.163.com
    username: plucknets@163.com
    password: RLJGCWQKGTFHOESU
    default-encoding: utf-8
  data:
    redis:
      host: localhost
      port: 6379
      password: ayame20#
      database: 0


# Mybatis-Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Custom configuration items
mail:
  verification-code:
    length: 5
    expiration: 900
  from-address: plucknets@163.com
  subject:
    verification: 验证 Kabe 的电子邮件地址
jwt:
  secret: Les_passionnés_de_technologie_font_avancer_le_monde
  expiration: 172800000
